services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    environment:
      ORACLE_PASSWORD: root
      APP_USER: SYSTEM
      APP_USER_PASSWORD: root
    ports:
      - '1521:1521'
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  oracle-data:
