# application-dev.yml

# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

# Spring Configuration
spring:
  # Docker Compose deaktivieren
  docker:
    compose:
      enabled: true

  # Haupt-Datenbank für eTutor Metadaten
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYSTEM
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:

  # Flyway Konfiguration
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    # clean-on-validation-error: true  <-- ENTFERNEN oder auskommentieren
    # clean-disabled: false            <-- ENTFERNEN oder auskommentieren

# Springdoc (Swagger UI)
springdoc:
  show-actuator: true

# API key definition (für eTutor Starter)
clients:
  api-keys:
    - name: task-administration
      key: task-admin-key
      roles:
        - CRUD
        - SUBMIT
    - name: jobe-server
      key: jobe-server-key
      roles:
        - SUBMIT
    - name: plag-check
      key: plag-check-key
      roles:
        - READ_SUBMISSION

# --- Konfiguration für das ORV Modul ---
jdbc:
  url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
  admin:
    username: SYSTEM
    password: root
  executor:
    username: SYSTEM
    password: root
  max-pool-size: 10
  max-lifetime: 1800000
  connection-timeout: 30000
