BEGIN EXECUTE IMMEDIATE 'DROP TABLE submission CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE task CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE task_group CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE task_group (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR2(255) NOT NULL,
                            description CLOB,
                            status VARCHAR2(20) DEFAULT 'draft' NOT NULL,
                            intensional_schema CLOB NOT NULL,
                            extensional_schema CLOB NOT NULL,
                            submit_inserts CLOB NOT NULL,
                            diagnose_inserts CLOB NOT NULL,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT chk_task_group_status CHECK (status IN ('draft', 'ready_for_approval', 'approved'))
) TABLESPACE USERS;

CREATE TABLE task (
                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      task_group_id NUMBER NOT NULL,
                      title VARCHAR2(255) NOT NULL,
                      description CLOB,
                      status VARCHAR2(20) DEFAULT 'draft' NOT NULL,
                      max_points NUMBER(10, 2) DEFAULT 1,
                      under_superview CLOB,
                      ref_superview CLOB,
                      solution CLOB NOT NULL,
                      test_query CLOB NOT NULL,
                      expected_identifier VARCHAR2(50),
                      missing_primitive_field_penalty NUMBER(10, 2),
                      missing_object_field_penalty NUMBER(10, 2),
                      missing_nested_table_penalty NUMBER(10, 2),
                      wrong_nested_table_type_penalty NUMBER(10, 2),
                      wrong_view_object_type_penalty NUMBER(10, 2),
                      wrong_oid_penalty NUMBER(10, 2),
                      wrong_content_penalty NUMBER(10, 2),
                      wrong_column_order_penalty NUMBER(10, 2),
                      wrong_superview_penalty NUMBER(10, 2),
                      CONSTRAINT fk_task_group FOREIGN KEY (task_group_id) REFERENCES task_group(id) ON DELETE CASCADE,
                      CONSTRAINT chk_task_status CHECK (status IN ('draft', 'ready_for_approval', 'approved'))
) TABLESPACE USERS;

CREATE TABLE submission (
                            id CHAR(36) DEFAULT LOWER(RAWTOHEX(SYS_GUID())) PRIMARY KEY,
                            task_id NUMBER NOT NULL,
                            user_id VARCHAR2(255) NOT NULL,
                            assignment_id VARCHAR2(255),
                            submission CLOB NOT NULL,
                            submission_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            language VARCHAR2(2) DEFAULT 'en' NOT NULL,
                            submission_mode VARCHAR2(20) NOT NULL,
                            feedback_level NUMBER DEFAULT 0 NOT NULL,
                            evaluation_result JSON,
                            points NUMBER(10, 2) DEFAULT 0,
                            grading_message CLOB,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_submission_task FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE
) TABLESPACE USERS;

CREATE INDEX idx_task_group_id ON task(task_group_id);
CREATE INDEX idx_submission_task_id ON submission(task_id);
